package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ProjectFileName is the filename FORGE looks for when discovering a
// project — at CWD or any ancestor directory.
const ProjectFileName = "forge.yaml"

// defaultProjectYAML is what `forge init` writes and what Discover
// falls back to when no forge.yaml is found anywhere up to the root.
// Keep in sync with the project's own forge.yaml at the repo root.
const defaultProjectYAML = `# FORGE project config — generated by 'forge init'.
# Edit and check into your repo to pin per-project bootstrap versions
# and resource defaults. Resource defaults are overridable per-env via
# --cpus / --memory / --disk on 'forge env create'.

bootstrap:
  k3s: v1.32.0+k3s1
  claude_code: latest
  helm: v3.20.2

defaults:
  cpus: 2
  memory: 4096   # MB
  disk: 20480    # MB
`

type ProjectConfig struct {
	Bootstrap BootstrapConfig `yaml:"bootstrap"`
	Defaults  ResourceConfig  `yaml:"defaults"`
}

type BootstrapConfig struct {
	K3s        string `yaml:"k3s"`
	ClaudeCode string `yaml:"claude_code"`
	Helm       string `yaml:"helm"`
}

type ResourceConfig struct {
	CPUs   int `yaml:"cpus"`
	Memory int `yaml:"memory"`
	Disk   int `yaml:"disk"`
}

// DefaultProjectYAML returns the canonical default forge.yaml content,
// suitable for writing via `forge init`.
func DefaultProjectYAML() []byte {
	return []byte(defaultProjectYAML)
}

// WriteDefaultProject creates a forge.yaml in dir using the embedded
// default content. Returns the absolute path of the written file.
// Errors if the file already exists, unless force is true.
func WriteDefaultProject(dir string, force bool) (string, error) {
	info, err := os.Stat(dir)
	if err != nil {
		return "", fmt.Errorf("checking %s: %w", dir, err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("%s is not a directory", dir)
	}
	target := filepath.Join(dir, ProjectFileName)
	if _, err := os.Stat(target); err == nil && !force {
		return "", fmt.Errorf("%s already exists", target)
	} else if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("checking %s: %w", target, err)
	}
	if err := os.WriteFile(target, []byte(defaultProjectYAML), 0o644); err != nil {
		return "", fmt.Errorf("writing %s: %w", target, err)
	}
	abs, err := filepath.Abs(target)
	if err != nil {
		return target, nil
	}
	return abs, nil
}

// LoadProject reads and validates a forge.yaml at the given path.
func LoadProject(path string) (ProjectConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ProjectConfig{}, fmt.Errorf("reading %s: %w", path, err)
	}
	cfg, err := loadProjectFromBytes(data)
	if err != nil {
		return ProjectConfig{}, fmt.Errorf("parsing %s: %w", path, err)
	}
	return cfg, nil
}

// Discover finds a forge.yaml by walking up from the current working
// directory. If none is found anywhere along the way, it returns the
// embedded defaults (equivalent to a freshly-`forge init`-ed file).
//
// The returned source is the absolute path of the file used, or an
// empty string when defaults were used — callers can surface that in
// debug output.
func Discover() (cfg ProjectConfig, source string, err error) {
	cwd, err := os.Getwd()
	if err != nil {
		return ProjectConfig{}, "", fmt.Errorf("getting working directory: %w", err)
	}
	if path := findProjectFile(cwd); path != "" {
		cfg, err = LoadProject(path)
		return cfg, path, err
	}
	cfg, err = loadProjectFromBytes([]byte(defaultProjectYAML))
	if err != nil {
		return ProjectConfig{}, "", fmt.Errorf("parsing embedded default forge.yaml: %w", err)
	}
	return cfg, "", nil
}

// findProjectFile walks upward from startDir looking for ProjectFileName.
// Returns the absolute path of the first match, or "" if it reaches the
// filesystem root without finding one.
func findProjectFile(startDir string) string {
	dir := startDir
	for {
		candidate := filepath.Join(dir, ProjectFileName)
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func loadProjectFromBytes(data []byte) (ProjectConfig, error) {
	var cfg ProjectConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return ProjectConfig{}, err
	}
	applyProjectDefaults(&cfg)
	if err := validateProject(cfg); err != nil {
		return ProjectConfig{}, err
	}
	return cfg, nil
}

func applyProjectDefaults(cfg *ProjectConfig) {
	if cfg.Defaults.CPUs == 0 {
		cfg.Defaults.CPUs = 2
	}
	if cfg.Defaults.Memory == 0 {
		cfg.Defaults.Memory = 4096
	}
	if cfg.Defaults.Disk == 0 {
		cfg.Defaults.Disk = 20480
	}
}

func validateProject(cfg ProjectConfig) error {
	if cfg.Bootstrap.K3s == "" {
		return fmt.Errorf("bootstrap.k3s is required in forge.yaml")
	}
	if cfg.Bootstrap.ClaudeCode == "" {
		return fmt.Errorf("bootstrap.claude_code is required in forge.yaml")
	}
	if cfg.Bootstrap.Helm == "" {
		return fmt.Errorf("bootstrap.helm is required in forge.yaml")
	}
	if cfg.Defaults.CPUs < 0 {
		return fmt.Errorf("defaults.cpus must not be negative")
	}
	if cfg.Defaults.Memory < 0 {
		return fmt.Errorf("defaults.memory must not be negative")
	}
	if cfg.Defaults.Disk < 0 {
		return fmt.Errorf("defaults.disk must not be negative")
	}
	return nil
}
